# Generated by Django 3.0 on 2019-12-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_auto_20191218_1332"),
    ]

    operations = [
        migrations.RemoveField(model_name="refundrecord", name="item",),
        migrations.AddField(
            model_name="refundrecord",
            name="pay",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="refunds",
                to="finance.PayRecord",
                verbose_name="缴费单id",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RefundRecordItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refund", models.FloatField(verbose_name="退款金额")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="refund_items",
                        to="finance.PayItem",
                        verbose_name="缴费项目id",
                    ),
                ),
            ],
            options={
                "verbose_name": "退款记录条目",
                "verbose_name_plural": "退款记录条目",
                "db_table": "refund_record_item",
            },
        ),
    ]
