# Generated by Django 3.0 on 2019-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_auto_20191218_2328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditrecord",
            name="result",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "通过"), (0, "未通过")],
                null=True,
                verbose_name="审核结果",
            ),
        ),
    ]
