# Generated by Django 3.0 on 2019-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorytype',
            name='price',
            field=models.FloatField(default=0, verbose_name='价格'),
            preserve_default=False,
        ),
    ]
