# Generated by Django 3.0 on 2019-12-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0002_laboratorytype_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="laboratory", name="check_part",),
        migrations.RemoveField(model_name="laboratory", name="commet",),
        migrations.RemoveField(model_name="laboratoryitem", name="modifier",),
        migrations.RemoveField(
            model_name="laboratoryitem", name="modify_time",
        ),
        migrations.AddField(
            model_name="laboratoryitem",
            name="check_part",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="检查部位"
            ),
        ),
        migrations.AddField(
            model_name="laboratoryitem",
            name="commet",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="注意事项"
            ),
        ),
    ]
