# Generated by Django 3.0 on 2019-12-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20191218_1332'),
        ('laboratory', '0004_auto_20191216_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='pay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratory', to='finance.PayRecord', verbose_name='缴费记录id'),
        ),
    ]
