# Generated by Django 3.0 on 2019-12-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_time', models.DateTimeField(auto_now_add=True, verbose_name='开始排队时间')),
            ],
            options={
                'db_table': 'wait_queue',
                'managed': False,
            },
        ),
    ]
