# Generated by Django 3.0 on 2019-12-03 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Medicine", "0001_initial"),
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        choices=[(0, "未缴费"), (1, "已缴费")],
                        default=0,
                        verbose_name="是否已经缴费",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="医生id",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="get_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="病人id",
                    ),
                ),
            ],
            options={
                "verbose_name": "处方",
                "verbose_name_plural": "处方",
                "db_table": "prescription",
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=32, verbose_name="用法")),
                ("ratio", models.CharField(max_length=64, verbose_name="服用频率")),
                (
                    "days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="服用时长"
                    ),
                ),
                ("commet", models.CharField(max_length=64, verbose_name="其他")),
                ("count", models.IntegerField(verbose_name="药物总数量")),
                (
                    "count_unit",
                    models.CharField(max_length=32, verbose_name="数量单位"),
                ),
                ("dosage", models.CharField(max_length=32, verbose_name="用量")),
                (
                    "dosage_unit",
                    models.CharField(max_length=32, verbose_name="用量单位"),
                ),
                (
                    "skin_test",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="皮试结果",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="prescription_items",
                        to="Medicine.Medicine",
                        verbose_name="药物id",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="items",
                        to="Outpatient.Prescription",
                        verbose_name="处方id",
                    ),
                ),
            ],
            options={
                "verbose_name": "处方条目",
                "verbose_name_plural": "处方条目",
                "db_table": "prescription_item",
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onset_date", models.DateField(verbose_name="发病日期")),
                (
                    "diagnosis",
                    models.CharField(max_length=255, verbose_name="诊断"),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, null=True, verbose_name="病情详情"
                    ),
                ),
                (
                    "patient_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="病人主诉"
                    ),
                ),
                (
                    "onset_history",
                    models.TextField(blank=True, null=True, verbose_name="发病史"),
                ),
                ("time", models.DateTimeField(verbose_name="就诊时间")),
                (
                    "medicine_history",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="药物史",
                    ),
                ),
                ("can_modify", models.BooleanField(verbose_name="是否可编辑")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "modify_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="修改时间"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_medical_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者id",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="medical_records",
                        to="auth.Group",
                        verbose_name="就诊科室",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="modified_medical_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="修改者id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="medical_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="病人id",
                    ),
                ),
            ],
            options={
                "verbose_name": "病历",
                "verbose_name_plural": "病历",
                "db_table": "medical_record",
            },
        ),
    ]
