# Generated by Django 3.0 on 2019-12-16 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='midifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifier_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='修改者id'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
