# Generated by Django 3.0 on 2019-12-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outpatient", "0002_auto_20191216_1604"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalrecord", old_name="user", new_name="patient",
        ),
    ]
