# Generated by Django 3.0 on 2019-12-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpatient", "0003_auto_20191216_1735"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="modify_time",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="修改时间"
            ),
        ),
    ]
