# Generated by Django 3.0 on 2019-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0004_medicinehandoutrecord_is_handout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinehandoutrecord",
            name="is_handout",
            field=models.BooleanField(default=0, verbose_name="是否已经发放"),
        ),
    ]
