# Generated by Django 3.0 on 2019-12-18 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medicine", "0005_auto_20191218_2001"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicinehandoutrecord",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="modified_medicine_handout_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改者id",
            ),
        ),
        migrations.AddField(
            model_name="medicinehandoutrecord",
            name="modify_time",
            field=models.DateTimeField(auto_now=True, verbose_name="修改时间"),
        ),
    ]
