# Generated by Django 3.0 on 2019-12-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20191218_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinehandoutrecord',
            name='is_handout',
        ),
        migrations.AddField(
            model_name='medicinehandoutrecord',
            name='handout_status',
            field=models.IntegerField(default=0, verbose_name='药品发放状态'),
        ),
    ]
