# Generated by Django 3.0 on 2019-12-04 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('is_delete', models.BooleanField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否从黑名单移除')),
                ('reason', models.CharField(blank=True, max_length=64, null=True, verbose_name='加入黑名单原因')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_black_lists', to=settings.AUTH_USER_MODEL, verbose_name='创建者id')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='is_black', to=settings.AUTH_USER_MODEL, verbose_name='病人id')),
            ],
            options={
                'verbose_name': '黑名单',
                'verbose_name_plural': '黑名单',
                'db_table': 'black_list',
            },
        ),
    ]
