# Generated by Django 3.0 on 2019-12-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191214_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogRecord',
        ),
    ]
