# Generated by Django 3.0 on 2019-12-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_delete_userlogrecord"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="age",),
    ]
