# Generated by Django 3.0 on 2019-12-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("user", "0004_remove_userprofile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupprofile",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_groups",
                to="auth.Group",
                verbose_name="父组id",
            ),
        ),
    ]
